title: Python for Neuroscience
author: Dr. Hagai Hargil, Zvi Baratz, Gal Ben-Zvi
logo: logo.png

execute:
  allow_errors: true

parse:
  myst_extended_syntax: true

repository:
  url: https://github.com/ZviBaratz/python_for_neuroscientists
  path_to_book: source/
  branch: main

html:
  home_page_in_navbar: true
  use_issues_button: true

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex

exclude_patterns: ["**/*_skip.ipynb*"]
